stages:
  - name: Build
    jobs:
      - name: BuildFrontend
        type: Build
        tasks:
          - name: InstallDependencies
            type: npm
            commands:
              - npm install
          - name: BuildApp
            type: npm
            commands:
              - npm run build

  - name: Dockerize
    jobs:
      - name: BuildDockerImage
        type: Build
        tasks:
          - name: DockerBuild
            type: Shell
            commands:
              - docker build -t my-frontend-app .
              - docker save my-frontend-app -o my-frontend-app.tar

  - name: Deploy
    jobs:
      - name: DeployToHTML5Repo
        type: Deploy
        tasks:
          - name: UploadToHTML5
            type: HTML5AppDeploy
            inputs:
              appName: MyFrontendApp
              appPath: build
              xsAppJson: xs-app.json
